# Generated by Django 6.0.1 on 2026-02-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the offer', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Offer image', null=True, upload_to='offer_images/')),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when offer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when offer was last updated')),
                ('user', models.ForeignKey(help_text='Business user who created this offer', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of this detail tier (e.g., 'Basic Package')", max_length=200)),
                ('revisions', models.IntegerField(default=0, help_text='Number of revisions included')),
                ('delivery_time_in_days', models.IntegerField(help_text='Delivery time in days')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this detail tier', max_digits=10)),
                ('features', models.TextField(help_text='Features included in this tier')),
                ('offer_type', models.CharField(help_text="Type of offer (e.g., 'basic', 'standard', 'premium')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when detail was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when detail was last updated')),
                ('offer', models.ForeignKey(help_text='The offer this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offer_app.offer')),
            ],
            options={
                'verbose_name': 'Offer Detail',
                'verbose_name_plural': 'Offer Details',
                'ordering': ['price'],
            },
        ),
    ]
