# Generated by Django 6.0.1 on 2026-02-02 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, default='', help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, default='', help_text="User's last name", max_length=100)),
                ('file', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(blank=True, default='', help_text="User's location", max_length=200)),
                ('tel', models.CharField(blank=True, default='', help_text='Phone number', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='User description or bio')),
                ('working_hours', models.CharField(blank=True, default='', help_text="Working hours (e.g., '9-17')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
